### ISSUE TITLE
Loading two questionnaires in one flow doesnt work

### ISSUE THREAD

**Issue by chamathpali** [isee4xai/iSeeCockpit#58]

**Comment by chamathpali** [comment]
#76

**Comment by anjanaw** [comment]
issue still exists on https://cockpit-dev.isee4xai.com/

**Comment by chamathpali** [comment]
@anjanaw i have found the root cause for this. but in order to fix it we will need to bring the two action buttons inside the questionnaire editor component. check below screenshot
![image](https://user-images.githubusercontent.com/5123109/220379091-8eaf5aad-910b-49da-9517-0b0411ede76d.png)

**Comment by chamathpali** [comment]
@anjanaw fixes are now deployed

**Comment by anjanaw** [comment]
Same workflow, second intent save questionnaire gives error
<img width="1230" alt="Screenshot 2023-03-31 at 10 31 27" src="https://user-images.githubusercontent.com/233262/229083363-2f06906e-24d4-493c-8a41-546ca0b6fe01.png">

**Comment by chamathpali** [comment]
@anjanaw i found the bug (it was a wrong state variable) and did some local testing. Can you do some testing of creation flows and close the issue if its all okay.

**Comment by anjanaw** [comment]
tested
