### ISSUE TITLE
Adding the same question twice

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeCockpit#59]
<img width="639" alt="Screenshot 2022-12-07 at 11 45 42" src="https://user-images.githubusercontent.com/233262/206171475-dd79853c-7184-4cef-aba6-f002dc84a335.png">

**Comment by chamathpali** [comment]
![Screenshot 2023-02-22 at 18 32 21](https://user-images.githubusercontent.com/5123109/220727637-3e41d8ce-c081-4004-ace6-7337d3d969fd.png)
